Parameters:

  # General
  
  Creator:
    Description: AWS username.
    Type: String

  # Networking

  SubnetId:
    Description: Must auto-assign IPv4 addresses. This is a temporary hack.
    Type: AWS::EC2::Subnet::Id

  VpcId:
    Description: The VPC id for image building.
    Type: AWS::EC2::VPC::Id

  # Infrastructure Configuration
  
  InstanceTypeOne:
    Description: EC2 type performing the build.
    Type: String
    Default: t3.small

  InstanceTypeTwo:
    Description: EC2 type performing the build.
    Type: String
    Default: t3.medium

  # Pipeline Configuration

  ImageTestsTimeout:
    Description: Max duration for image testing.
    Type: Number
    Default: 120

  # Buckets
  
  LoggingBucket:
    Description: Logs go here.
    Type: String

  ComponentBucket:
    Description: Components are here.
    Type: String

Resources:

  # TODO: Rebuild the Dev stack so we get automatic public IPv4
  # NOTE: Can't until Isle-Dev is out of the way.

  # IAM
  
  ImageBuilderIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Description: Allows ImageBuilder to operate in fsulib's environments.
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/EC2InstanceProfileForImageBuilder
      Path: '/instance_roles/'
      Policies:
        - PolicyName: LogBucketPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 
                  - s3:ListBucket 
                Resource: !Sub arn:aws:s3:::${LoggingBucket}
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource: !Sub arn:aws:s3:::${LoggingBucket}/image-builder/*
      Tags:
        - Key: Name
          Value: Image Builder IAM Role
        - Key: lib:created-by
          Value: !Ref Creator

  ImageBuilderInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: '/instance_profiles/'
      Roles:
        - !Ref ImageBuilderIamRole
 
  # Security Group
  
  ImageBuilderSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: A security group for ImageBuilder instances.
      GroupName: ImageBuilderInstanceSg
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Open to World
          IpProtocol: '-1'
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: ImageBuilder SG
        - Key: lib:created-by
          Value: !Ref Creator
        - Key: lib:env
          Value: dev

  # SNS Topic

  ImageBuilderSnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: ImageBuilderTopic
      Tags:
        - Key: Name
          Value: ImageBuilderSnsTopic
        - Key: Creator
          Value: !Ref Creator

  # NOTE Temporary
  
  ImageBuilderSnsTopicSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: mshackelford@fsu.edu
      Protocol: email
      TopicArn: !Ref ImageBuilderSnsTopic

  ImageBuilderSnsTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal:
            Service:
              - imagebuilder.amazonaws.com
          Action:
            - sns:Publish
          Resource: !Ref ImageBuilderSnsTopic
      Topics:
        - !Ref ImageBuilderSnsTopic

  # Components

  UbuntuBaseUpdateComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      ChangeDescription: 'Formalized version from a CF template.'
      Uri: !Sub s3://${ComponentBucket}/imagebuilder/components/component-linux-update.yaml
      Description: Updates the managed base image.
      Name: Patch Base Ubuntu Image
      Platform: Linux
      SupportedOsVersions:
        - Ubuntu 20
        - Ubuntu 18
      Tags:
        'Name': 'Ubuntu Base Update Component'
        'lib:distribution': 'Ubuntu'
        'lib:created-by': !Ref Creator
      Version: 1.0.0

  UbuntuInstallAwsToolsComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      ChangeDescription: 'Formalized version from a CF template.'
      Uri: !Sub s3://${ComponentBucket}/imagebuilder/components/component-awstools-installation.yaml
      Description: Installs jq, awscli, CloudWatch Atent, EFS Mount Helper, and the CloudFormation helper scripts.
      Name: Install AWS Tools and Dependencies
      Platform: Linux
      SupportedOsVersions:
        - Ubuntu 20
        - Ubuntu 18
      Tags:
        'Name': 'Ubuntu AWS Tools Installation Component'
        'lib:distribution': 'Ubuntu'
        'lib:created-by': !Ref Creator
      Version: 1.1.0

  UbuntuInstallDockerComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      ChangeDescription: 'Formalized version from a CF template.'
      Uri: !Sub s3://${ComponentBucket}/imagebuilder/components/component-docker-installation.yaml
      Description: Installs the Docker GPG key, repo, application, and dependencies.
      Name: Install Docker
      Platform: Linux
      SupportedOsVersions:
        - Ubuntu 20
        - Ubuntu 18
      Tags:
        'Name': 'Ubuntu Docker Installation Component'
        'lib:distribution': 'Ubuntu'
        'lib:created-by': !Ref Creator
      Version: 1.0.1

  # Recipes
  
  Ubuntu1804DockerHostImageRecipe:
    Type: AWS::ImageBuilder::ImageRecipe
    Properties:
      Components:
        - ComponentArn: !GetAtt UbuntuBaseUpdateComponent.Arn
        - ComponentArn: !GetAtt UbuntuInstallAwsToolsComponent.Arn
        - ComponentArn: !GetAtt UbuntuInstallDockerComponent.Arn
      Description: Patches OS, installs standard AWS tools, installs Docker-CE.
      Name: Docker Host Image for Ubuntu 18_04
      ParentImage: arn:aws:imagebuilder:us-east-1:aws:image/ubuntu-server-18-lts-x86/x.x.x
      Tags:
        'lib:created-by': !Ref Creator
        'lib:distribution': Ubuntu 18.04
        'lib:dockerhost': true
      Version: 1.0.1

  Ubuntu2004DockerHostImageRecipe:
    Type: AWS::ImageBuilder::ImageRecipe
    Properties:
      Components:
        - ComponentArn: !GetAtt UbuntuBaseUpdateComponent.Arn
        - ComponentArn: !GetAtt UbuntuInstallAwsToolsComponent.Arn
        - ComponentArn: !GetAtt UbuntuInstallDockerComponent.Arn
      Description: Patches OS, installs standard AWS tools, installs Docker-CE.
      Name: Docker Host Image for Ubuntu 20_04
      ParentImage: arn:aws:imagebuilder:us-east-1:aws:image/ubuntu-server-20-lts-x86/x.x.x
      Tags:
        "lib:created-by": !Ref Creator
        "lib:distribution": Ubuntu 20.04
        "lib:dockerhost": true
      Version: 1.0.1

  Ubuntu1804StandardImageRecipe:
    Type: AWS::ImageBuilder::ImageRecipe
    Properties:
      Components:
        - ComponentArn: !GetAtt UbuntuBaseUpdateComponent.Arn
        - ComponentArn: !GetAtt UbuntuInstallAwsToolsComponent.Arn
      Description: Patches OS, installs standard AWS tools.
      Name: Standard Image for Ubuntu 18_04
      ParentImage: arn:aws:imagebuilder:us-east-1:aws:image/ubuntu-server-18-lts-x86/x.x.x
      Tags:
        "lib:created-by": !Ref Creator
        "lib:distribution": Ubuntu 18.04
        "lib:dockerhost": false
      Version: 1.0.1

  Ubuntu2004StandardImageRecipe:
    Type: AWS::ImageBuilder::ImageRecipe
    Properties:
      Components:
        - ComponentArn: !GetAtt UbuntuBaseUpdateComponent.Arn
        - ComponentArn: !GetAtt UbuntuInstallAwsToolsComponent.Arn
      Description: Patches OS, installs standard AWS tools.
      Name: Standard Image for Ubuntu 20_04
      ParentImage: arn:aws:imagebuilder:us-east-1:aws:image/ubuntu-server-20-lts-x86/x.x.x
      Tags:
        "lib:created-by": !Ref Creator
        "lib:distribution": Ubuntu 20.04
        "lib:dockerhost": false
      Version: 1.0.1

  # Infrastructure Configuration 

  SimpleInfrastructureConfiguration:
    Type: AWS::ImageBuilder::InfrastructureConfiguration
    Properties:
      Description: A simple infrastucture config intended for running simple components.
      InstanceProfileName: !Ref ImageBuilderInstanceProfile
      InstanceTypes:
        - !Ref InstanceTypeOne
        - !Ref InstanceTypeTwo
      Logging:
        S3Logs:
          S3BucketName: logging.lib.fsu.edu
          S3KeyPrefix: image-builder
      Name: Simple Infrastructure Configuration
      ResourceTags:
        "lib:created-by": "ImageBuilder Service"
        "lib:env": "dev"
      SecurityGroupIds:
        - !Ref ImageBuilderSecurityGroup
      SnsTopicArn: !Ref ImageBuilderSnsTopic
      SubnetId: !Ref SubnetId
      Tags:
        "Name": "Simple ImageBuilder Infrastructure"
        "lib:created-by": !Ref Creator
      TerminateInstanceOnFailure: true

  # Distribution Configurations

  DockerHostUbuntu1804Distribution:
    Type: AWS::ImageBuilder::DistributionConfiguration
    Properties:
      Description: Ubuntu 1804 DockerHost Distribution
      Distributions:
        - AmiDistributionConfiguration:
            AmiTags:
              Name: DockerHost-Ubuntu-1804
              'lib:env': any
              'lib:app': any
              'lib:build-version': build-{{imagebuilder:buildVersion}}
            Description: Ubuntu 1804 DockerHost
            Name: DockerHost-Ubuntu-1804_{{imagebuilder:buildDate}}
          Region: !Ref AWS::Region
      Name: DockerHost Ubuntu 1804 Image Distribution
      Tags:
        "Name": DockerHost Ubuntu 1804 Image Distribution
        "lib:created-by": !Ref Creator

  DockerHostUbuntu2004Distribution:
    Type: AWS::ImageBuilder::DistributionConfiguration
    Properties:
      Description: Ubuntu 2004 DockerHost Distribution
      Distributions:
        - AmiDistributionConfiguration:
            AmiTags:
              Name: DockerHost-Ubuntu-2004
              'lib:env': any
              'lib:app': any
              'lib:build-version': build-{{imagebuilder:buildVersion}}
            Description: Ubuntu 2004 DockerHost
            Name: DockerHost-Ubuntu-2004_{{imagebuilder:buildDate}}
          Region: !Ref AWS::Region
      Name: DockerHost Ubuntu 2004 Image Distribution
      Tags:
        "Name": DockerHost Ubuntu 2004 Image Distribution
        "lib:created-by": !Ref Creator

  StandardUbuntu1804Distribution:
    Type: AWS::ImageBuilder::DistributionConfiguration
    Properties:
      Description: Ubuntu 1804 Standard Distribution
      Distributions:
        - AmiDistributionConfiguration:
            AmiTags:
              Name: Standard-Ubuntu-1804
              'lib:env': any
              'lib:app': any
              'lib:build-version': build-{{imagebuilder:buildVersion}}
            Description: Ubuntu 1804 Standard
            Name: Standard-Ubuntu-1804_{{imagebuilder:buildDate}}
          Region: !Ref AWS::Region
      Name: Standard Ubuntu 1804 Image Distribution
      Tags:
        "Name": Standard Ubuntu 1804 Image Distribution
        "lib:created-by": !Ref Creator
        
  StandardUbuntu2004Distribution:
    Type: AWS::ImageBuilder::DistributionConfiguration
    Properties:
      Description: Ubuntu 2004 Standard Distribution
      Distributions:
        - AmiDistributionConfiguration:
            AmiTags:
              Name: Standard-Ubuntu-2004
              'lib:env': any
              'lib:app': any
              'lib:build-version': build-{{imagebuilder:buildVersion}}
            Description: Ubuntu 2004 Standard
            Name: Standard-Ubuntu-2004_{{imagebuilder:buildDate}}
          Region: !Ref AWS::Region
      Name: Standard Ubuntu 2004 Image Distribution
      Tags:
        "Name": Standard Ubuntu 2004 Image Distribution
        "lib:created-by": !Ref Creator

  # Pipeline Configurations

  # TODO Automated build scheduling based on dependency updates
  # TODO Properties for Status (ENABLED|DISABLED)

  Ubuntu1804DockerHostPipeline:
    Type: AWS::ImageBuilder::ImagePipeline
    Properties:
      Description: Builds and distributes a DockerHost 1804 image
      DistributionConfigurationArn: !Ref DockerHostUbuntu1804Distribution
      EnhancedImageMetadataEnabled: true
      ImageRecipeArn: !Ref Ubuntu1804DockerHostImageRecipe
      ImageTestsConfiguration:
        ImageTestsEnabled: true
        TimeoutMinutes: !Ref ImageTestsTimeout
      InfrastructureConfigurationArn: !Ref SimpleInfrastructureConfiguration
      Name: DockerHost Pipeline for Ubuntu 1804
      Status: ENABLED
      Tags:
        Name: Ubuntu 1804 DockerHost Pipeline
        'lib:created-by': mshackelford
        'lib:distribution': Ubuntu1804
        'lib:dockerhost': true
    
  Ubuntu2004DockerHostPipeline:
    Type: AWS::ImageBuilder::ImagePipeline
    Properties:
      Description: Builds and distributes a DockerHost 1804 image
      DistributionConfigurationArn: !Ref DockerHostUbuntu2004Distribution
      EnhancedImageMetadataEnabled: true
      ImageRecipeArn: !Ref Ubuntu2004DockerHostImageRecipe
      ImageTestsConfiguration:
        ImageTestsEnabled: true
        TimeoutMinutes: !Ref ImageTestsTimeout
      InfrastructureConfigurationArn: !Ref SimpleInfrastructureConfiguration
      Name: DockerHost Pipeline for Ubuntu 2004
      Status: ENABLED
      Tags:
        Name: Ubuntu 2004 DockerHost Pipeline
        'lib:created-by': mshackelford
        'lib:distribution': Ubuntu1804
        'lib:dockerhost': true
    
  Ubuntu1804StandardPipeline:
    Type: AWS::ImageBuilder::ImagePipeline
    Properties:
      Description: Builds and distributes a DockerHost 1804 image
      DistributionConfigurationArn: !Ref StandardUbuntu1804Distribution
      EnhancedImageMetadataEnabled: true
      ImageRecipeArn: !Ref Ubuntu1804StandardImageRecipe
      ImageTestsConfiguration:
        ImageTestsEnabled: true
        TimeoutMinutes: !Ref ImageTestsTimeout
      InfrastructureConfigurationArn: !Ref SimpleInfrastructureConfiguration
      Name: Standard Pipeline for Ubuntu 1804
      Status: ENABLED
      Tags:
        Name: Ubuntu 1804 Standard Pipeline
        'lib:created-by': mshackelford
        'lib:distribution': Ubuntu1804
        'lib:dockerhost': false
    
  Ubuntu2004StandardPipeline:
    Type: AWS::ImageBuilder::ImagePipeline
    Properties:
      Description: Builds and distributes a DockerHost 2004 image
      DistributionConfigurationArn: !Ref StandardUbuntu2004Distribution
      EnhancedImageMetadataEnabled: true
      ImageRecipeArn: !Ref Ubuntu2004StandardImageRecipe
      ImageTestsConfiguration:
        ImageTestsEnabled: true
        TimeoutMinutes: !Ref ImageTestsTimeout
      InfrastructureConfigurationArn: !Ref SimpleInfrastructureConfiguration
      Name: Standard Pipeline for Ubuntu 2004
      Status: ENABLED
      Tags:
        Name: Ubuntu 2004 Standard Pipeline
        'lib:created-by': mshackelford
        'lib:distribution': Ubuntu2004
        'lib:dockerhost': false
  
Outputs:
  CompUbuntuBaseUpdateArn:
    Value: !Ref UbuntuBaseUpdateComponent
    Export:
      Name: UbuntuBaseUpdateComponent

  CompUbuntuAwsToolsArn:
    Value: !Ref UbuntuInstallAwsToolsComponent
    Export:
      Name: UbuntuInstallAwsToolsComponent
    
  CompUbuntuDockerArn:
    Value: !Ref UbuntuInstallDockerComponent
    Export:
      Name: UbuntuInstallDockerComponent

  InfraSimpleConfig:
    Value: !Ref SimpleInfrastructureConfiguration
    Export:
      Name: SimpleInfrastructureConfiguration

  IamRoleArn:
    Value: !GetAtt ImageBuilderIamRole.Arn
    Export:
      Name: ImageBuilderIamRoleArn

  IamRoleName:
    Value: !Ref ImageBuilderIamRole
    Export:
      Name: ImageBuilderIamRoleName

  InstanceProfileArn:
    Value: !GetAtt ImageBuilderInstanceProfile.Arn
    Export:
      Name: ImageBuilderInstanceProfileArn

  InstanceProfileName:
    Value: !Ref ImageBuilderInstanceProfile
    Export:
      Name: ImageBuilderInstanceProfileName

  SnsTopicArn:
    Value: !Ref ImageBuilderSnsTopic
    Export:
      Name: ImageBuilderSnsTopicArn

  LogBucket:
    Value: !Ref LoggingBucket
    Export:
      Name: LoggingBucket

  CompBucket:
    Value: !Ref ComponentBucket
    Export:
      Name: ComponentBucket

# vim: set fdm=indent:
